### ISSUE TITLE
New presentation submission requires JWT

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/ssi-service#381] opened 2023-04-12 20:49 UTC
Calling PUT http://localhost:8080/v1/presentations/submissions requires a submissionJwt but the service has no way to form it

{
  "submissionJwt": "<string>"
}

**Comment by decentralgabe** [comment] 2023-04-12 20:54
@nitro-neal duplicate of https://github.com/TBD54566975/ssi-sdk/issues/165 ?

**Comment by decentralgabe** [comment] 2023-04-13 03:50
This is by design, as the service does not construct submissions, clients do.

The [sdk exposes methods](https://github.com/TBD54566975/ssi-sdk/blob/main/credential/exchange/submission.go#L127) to help construct submissions.

**Closed by decentralgabe** 2023-04-13 03:50 UTC
Labels: bug

**Comment by nitro-neal** [comment] 2023-04-13 17:02
I think there should be some way for someone who only has access to SSI-Service to use all functionality inside SSI-Service.

Kind of a strange workflow that they are given an object and have to JWT-ify it on their own means, not knowing if it will work or not.

We can have a generic route that will JWT any object and sign it with given did?

**Comment by decentralgabe** [comment] 2023-04-13 17:08
Sure, but what's the use case for an SSI service submitting a submission to itself?
